### ISSUE TITLE
pomuzcie

### ISSUE THREAD

**Issue by rydernyga** [CrosRoad95/PYSTORIES#2]
Witam nie zapisuje mi ani repki ani kasy po rc, baza danych podpieta. wchodze po rc loguje sie ale kasy i repki juz nie ma. Prosze o pomoc jest to moj 1 serwer.
Siema mam problem z panelem logowania na serwerze pomógł by ktoś?

błędy w db3
WARNING: [bazadanych]/pystories-db/s_db.lua:14: dbPoll failed; Unknown column 'znajdzki' in 'field list'

ERROR: [skrypty]/pystories-logging/s_logging.lua:40: exports: Call to non-running server resource (pystories-notifications) [string "?"]
Mógłby mnie ktoś naakierować zeby napisać prace ? miałaby to byc praca czyszczenie nagrobków wchodzisz w marker klikassz "e" idziesz do nagrobku i jest animacja klękania i dostajesz kase i pokazuje sie nastepny punkt zeby zakonczyc trzeba wejsc w marker

  |  
-- | --
Mam problem, wyskakują takie errory w debugscript 3Nie moge sie zalogowac ani zarejestrowachttps://imgur.com/a/st8WIJWZa pomoc oczywiście piwko

Witam mam problem dokladnie ze skryptem "psrpg-nametags" poniewaz nie widze cen pojazdow do ktorych sie zblizam oraz pojazdy "publiczne" rowniez nie posiadaja takowego opisu ponizej podsylam screen'a z debugscripta

https://imgur.com/a/lPMJLH9
Hej, zrobiłem serwer prywatny dla kilku znajomych, chcielibyśmy pograć na gamemodzie RPG, ale gdy wgrywam jakąkolwiek paczke, nie działa admin panel
gdy chce zresetować resource admina to okazuje się, że go nie ma, chociaż wszystko w plikach jest. Za pomoc stawiam piwko!
Witam mam taki problem, że każdy radar powoduje lagi. Co dziwne po wyłączeniu radaru lagi ustają, a po zrestartowaniu skryptu vehicles również ustają, lecz na około 5-10 minut. Po wyłączeniu radaru lagów nie ma.

Za pomoc repka i piwko gwarantowane
Witam przychodze z problemem , wgrałem sobię paczke przerobiłem ją i zauważyłem błąd https://imgur.com/a/C1C1Ef4 ( w ogrpg-db nic nie ruszałem)
stawiam zimne piwko za pomoc
Witam, mam taki problem otóż nie działa mi kompletnie prawko, można wsiadać do auta mimo tego, że nie masz wcale prawka. Wszystko jest podłączone pod ACL i również zmienione ogrpg na DB2.
Bardzo proszę o pomoc, będę bardzo wdzięczny i zarzucę zimnym :piwo: ;)

Czesc mam klopot z zrobieniem MK3 MK4 i lgbt licznik ogarne ale prosil bym o kontakt na squorczan#* lub pod postem Komentarz NotPaladyn dodany 2021-02-01, 20:42Skoro piszesz post o pomoc na forum to tutaj otrzymasz pomoc, nie dodawaj następnym razem swojego discorda do postu
--
Ostatnio zmieniony przez NotPaladyn 2021-02-01, 20:41, w całości zmieniany 1 raz

**Comment by kubaziom** [comment]
acha

**Comment by xsvtn** [comment]
aha

**Comment by 4Whitee** [comment]
tak

**Comment by boversoneg** [comment]
tak
